server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8081
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      # oneToMany시에 in query 자동 작성
      default_batch_fetch_size: 100
    # db session controller까지 가져오기
    open-in-view: false
  cache:
    type: simple
  redis:
    port: ${REDIS_PORT}
    host: ${HOST_NAME}
    username: ${REDIS_USERNAME}
    password: ${REDIS_PASSWORD}

logging:
  level:
    '[com.triplea.triplea]': DEBUG # DEBUG 레벨부터 에러 확인할 수 있게 설정하기
    '[org.hibernate.type]': TRACE # 콘솔 쿼리에 ? 에 주입된 값 보기

application:
  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: ${SMTP_PORT}
    socketFactory-class: javax.net.ssl.SSLSocketFactory
    supplier: ${SMTP_SUPPLIER}
    from-mail: ${SMTP_FROM}

jwt:
  subject: triple-a
  secret: IyRQvqcFu4I3zWZS

moya:
  token: ${MOYA_TOKEN}
tiingo:
  token: ${TIINGO_TOKEN}
step-pay:
  secret-token: ${STEPPAY_SECRET}
  product-code: ${STEPPAY_PRODUCT}
  price-code: ${STEPPAY_PRICE}
translate:
  token: ${WISE_TOKEN}
  openai-api-key: ${CHATGPT_OPENAI_API_KEY}
  papago:
    client-id: ${PAPAGO_ID}
    client-secret: ${PAPGO_SECRET}